### ISSUE TITLE
Questions regarding the ID type features

### ISSUE THREAD

**Issue by pandasMX** [CHIANGEL/MAP-CODE#2]
Hi, in the paper, you mentioned:

> Avazu originally contains 23 fields with categorical features.
We remove the id field that has a unique value for each data
sample

If the id fields were removed during pre-training, the input size will be different from finetuning on CTR task. As a result, the MLP layers in the model will have different sizes. How do you re-use the pre-trained weights in the MLP layers on CTR task if the size do not match?

**Comment by CHIANGEL** [comment]
This operation is done during the data preprocessing before both pretraining & finetuning stage. That is, the data ID field is not contained for both pretraining and finetuning. This operation is generally adopted by most of CTR papers, since the data ID is the column indicating the row index actually.

**Comment by pandasMX** [comment]
Oh i see, it's the row id not something like itemid/userid
